DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Juomat CASCADE;
DROP TABLE IF EXISTS Varasto CASCADE;
DROP TABLE IF EXISTS Asiakkaat CASCADE;
DROP TABLE IF EXISTS Kirjanpito CASCADE;
DROP TABLE IF EXISTS Loki CASCADE;
DROP TABLE IF EXISTS abc CASCADE;
DROP TABLE IF EXISTS Asiakas CASCADE;